#!/bin/bash
USERNAME="${1:-}"
PASSWORD="${2:-}"

LOGFILE="/var/log/install_debug.log"
exec >> "$LOGFILE" 2>&1

echo "====== $(date) ======"
echo "USERNAME: '$USERNAME'"
echo "PASSWORD: '${#PASSWORD} characters'"  # log alleen lengte, niet de waarde zelf
echo "Running as user: $(whoami)"
echo ""


sudo adduser -m "$USERNAME"
echo "$USERNAME:$PASSWORD" | sudo chpasswd

echo "Running apt update"
sudo apt-get update -y

echo "Running apt upgrade"
sudo apt-get upgrade -y

echo "Installing nmap"
sudo apt install nmap -y

echo "Installing snap"
sudo apt install snapd -y

echo "Installing postman"
sudo snap install postman

echo "Installing Wireshark"
echo "wireshark-common wireshark-common/install-setuid boolean true" | sudo debconf-set-selections
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y wireshark

echo "Installing curl"
sudo apt install curl -y

echo "Installing jq"
sudo apt install jq -y

echo "installing passwd"
sudo apt install passwd -y

echo "Installing VSCode"
sudo snap install code --classic

echo "Install unzip"
sudo apt install unzip -y

echo "Installing Java"
sudo add-apt-repository ppa:openjdk-r/ppa -y
sudo apt update -y
sudo apt install openjdk-21-jdk -y

echo "Installing Burp Suite"
download_url="https://portswigger.net/burp/releases/download?product=community&type=jar"
wget --output-document=burpsuite_community.jar "$download_url"
sudo mkdir -p /opt/burp
sudo mv burpsuite_community.jar /opt/burp/
echo -e '#!/bin/bash\njava -jar /opt/burp/burpsuite_community.jar' | sudo tee /usr/local/bin/burp
sudo chmod +x /usr/local/bin/burp
cat <<EOF | sudo tee /usr/share/applications/burp.desktop
[Desktop Entry]
Name=Burp Suite Community
Exec=java -jar /opt/burp/burpsuite_community.jar
Icon=utilities-terminal
Type=Application
Categories=Utility;
EOF
export VAULT_ADDR=http://172.200.72.230:8200

echo "Installing Oracle Developer VScode extension"
runuser -l azureadmin -c 'code --install-extension Oracle.oracledevtools --force'

echo "Installing git"
sudo apt install git -y

echo "Installing python"
sudo apt install python -y
sudo apt install python3 -y

echo "Installing mitm proxy"
sudo apt install mitmproxy -y

echo "Setting up ubuntu desktop"
sudo apt install xrdp -y
sudo systemctl enable xrdp
sudo systemctl start xrdp
sudo apt install ubuntu-desktop -y

echo "install pentesttools"
sudo git clone https://x-token-auth:ATCTT3xFfGN0eC-nRrpwtw90xTakZi6E0iwiwRF-MLUJ0OEyVDKQvod05eSwqvi3mw4wc4e_iPc4UD1m2yZIkbadVVlfXgRdCtWm3qKNgB7VFpvhzjvrEEjIYjPWAxnLmzxJ3DM6_JgY2VrSc91q-UfvrXZDc6R5uB2u88rLMAtyYquuBVBf11U=B6AA6BC9@bitbucket.org/flod-marnix/pentestscripts.git /opt/pentesttools

cat <<EOF | sudo tee /usr/share/applications/oracleenum.desktop
[Desktop Entry]
Name=Oracle Enumeration Script
Exec=python3 /opt/pentesttools/enum_oracle.py
Icon=utilities-terminal
Type=Application
Categories=Utility;
Terminal=true
EOF

cat <<EOF | sudo tee /usr/share/applications/oraclevuln.desktop
[Desktop Entry]
Name=Oracle Password Script
Exec=python3 /opt/pentesttools/vuln_oracle.py
Icon=utilities-terminal
Type=Application
Categories=Utility;
Terminal=true
EOF

sudo chmod +x /usr/share/applications/oracle*.desktop

user_home="/home/$USERNAME"
sudo mkdir -p "$user_home/Desktop"
sudo cp /usr/share/applications/oracle*.desktop "$user_home/Desktop/"
sudo chown "$USERNAME:$USERNAME" "$user_home/Desktop/"*.desktop
sudo chmod +x "$user_home/Desktop/"*.desktop

echo "Setting op bao cli"
wget https://github.com/openbao/openbao/releases/download/v2.2.2/bao_2.2.2_linux_amd64.deb
sudo dpkg -i bao_2.2.2_linux_amd64.deb

USER_BASHRC="/home/$USERNAME/.bashrc"

# Zorg dat .bashrc bestaat (sommige minimal images hebben hem niet)
if [ ! -f "$USER_BASHRC" ]; then
  echo "# .bashrc autogenerated by install_apps.sh" | sudo tee "$USER_BASHRC" > /dev/null
  sudo chown "$USERNAME:$USERNAME" "$USER_BASHRC"
fi

VAULT_ADDR_VALUE="http://172.200.72.230:8200"

# Voeg toe als het nog niet bestaat
if grep -q "export VAULT_ADDR=" "$USER_BASHRC"; then
  echo "VAULT_ADDR staat al in $USER_BASHRC. Bijwerken..."
  sudo sed -i "s|export VAULT_ADDR=.*|export VAULT_ADDR='$VAULT_ADDR_VALUE'|" "$USER_BASHRC"
else
  echo "export VAULT_ADDR='$VAULT_ADDR_VALUE'" | sudo tee -a "$USER_BASHRC" > /dev/null
  echo "✅ VAULT_ADDR toegevoegd aan $USER_BASHRC"
fi

sudo usermod -aG sudo,video,audio,ssl-cert,xrdp $USERNAME
echo "startxfce4" | sudo tee /home/$USERNAME/.xsession > /dev/null
sudo chmod +x /home/$USERNAME/.xsession
sudo chown $USERNAME:$USERNAME /home/$USERNAME/.xsession
sudo runuser -l $USERNAME -c 'touch ~/.Xauthority && chmod 600 ~/.Xauthority'
sudo systemctl restart xrdp

sudo ls -la /home/$USERNAME/
sudo groups $USERNAME
sudo cat /home/azureadmin/.xsession
sudo cat /home/$USERNAME/.xsession


